SKILL_CATEGORIES = {
    "soft_skills": [
        "communication",
        "teamwork",
        "leadership",
        "problem-solving",
        "time-management",
        "adaptability",
        "creativity",
        "flexibility",
        "self-motivation",
        "attention-to-detail",
        "critical-thinking",
        "decision-making",
        "collaboration",
    ],
    # ... (rest of existing SKILL_CATEGORIES content)
}

JOB_SKILLS_MAP = {
    "frontend": [
        "html",
        "css",
        "javascript",
        "typescript",
        "react",
        "angular",
        "vue",
        "webpack",
        "sass",
        "less",
        "responsive design",
        "web accessibility",
        "redux",
        "jest",
        "cypress",
    ],
    "backend": [
        "python",
        "java",
        "nodejs",
        "php",
        "ruby",
        "go",
        "sql",
        "nosql",
        "rest api",
        "graphql",
        "microservices",
        "docker",
        "kubernetes",
    ],
    "fullstack": [
        "javascript",
        "python",
        "java",
        "sql",
        "react",
        "angular",
        "nodejs",
        "rest api",
        "html",
        "css",
        "git",
        "docker",
    ],
    "data": [
        "python",
        "r",
        "sql",
        "pandas",
        "numpy",
        "scikit-learn",
        "tensorflow",
        "pytorch",
        "tableau",
        "power bi",
        "hadoop",
        "spark",
        "vue",
        "svelte",
        "next.js",
        "nuxt.js",
        "webpack",
        "babel",
        "typescript",
        "redux",
        "graphql",
        "rest api",
        "soap",
        "xml",
        "json",
    ],
    "databases": [
        "sql",
        "mysql",
        "postgresql",
        "mongodb",
        "oracle",
        "redis",
        "elasticsearch",
        "dynamodb",
        "cassandra",
        "sqlite",
        "mariadb",
        "neo4j",
        "couchdb",
        "firebase",
        "supabase",
    ],
    "cloud_platforms": [
        "aws",
        "azure",
        "gcp",
        "digitalocean",
        "heroku",
        "netlify",
        "vercel",
        "cloudflare",
        "alibaba cloud",
        "ibm cloud",
        "oracle cloud",
    ],
    "devops_tools": [
        "git",
        "docker",
        "kubernetes",
        "jenkins",
        "travis ci",
        "circle ci",
        "terraform",
        "ansible",
        "puppet",
        "chef",
        "prometheus",
        "grafana",
        "elk stack",
        "nginx",
        "apache",
    ],
    "testing": [
        "selenium",
        "junit",
        "testng",
        "cypress",
        "jest",
        "mocha",
        "chai",
        "puppeteer",
        "postman",
        "soapui",
        "jmeter",
        "gatling",
        "cucumber",
        "protractor",
        "karma",
        "pytest",
        "phpunit",
        "rspec",
        "testcafe",
    ],
    "project_management": [
        "jira",
        "trello",
        "asana",
        "basecamp",
        "monday.com",
        "clickup",
        "confluence",
        "notion",
        "microsoft project",
        "smartsheet",
        "agile",
        "scrum",
        "kanban",
        "waterfall",
        "prince2",
    ],
    "design_tools": [
        "figma",
        "sketch",
        "adobe xd",
        "photoshop",
        "illustrator",
        "indesign",
        "after effects",
        "premiere pro",
        "invision",
        "zeplin",
        "principle",
    ],
    "machine_learning": [
        "tensorflow",
        "pytorch",
        "scikit-learn",
        "keras",
        "opencv",
        "pandas",
        "numpy",
        "scipy",
        "matplotlib",
        "seaborn",
        "nltk",
        "spacy",
        "hugging face",
    ],
    "mobile_development": [
        "android",
        "ios",
        "react native",
        "flutter",
        "xamarin",
        "ionic",
        "swift",
        "kotlin",
        "objective-c",
        "mobile testing",
        "responsive design",
    ],
    "security": [
        "cybersecurity",
        "encryption",
        "oauth",
        "jwt",
        "authentication",
        "authorization",
        "penetration testing",
        "security testing",
        "owasp",
        "ssl/tls",
        "firewall",
        "vpn",
    ],
}


# Define skill mappings for common job titles
JOB_SKILLS_MAP = {
    "frontend": [
        "html",
        "css",
        "javascript",
        "typescript",
        "react",
        "angular",
        "vue",
        "webpack",
        "sass",
        "less",
        "responsive design",
        "web accessibility",
        "redux",
        "jest",
        "cypress",
    ],
    "backend": [
        "python",
        "java",
        "nodejs",
        "php",
        "ruby",
        "go",
        "sql",
        "nosql",
        "rest api",
        "graphql",
        "microservices",
        "docker",
        "kubernetes",
    ],
    "fullstack": [
        "javascript",
        "python",
        "java",
        "sql",
        "react",
        "angular",
        "nodejs",
        "rest api",
        "html",
        "css",
        "git",
        "docker",
    ],
    "data": [
        "python",
        "r",
        "sql",
        "pandas",
        "numpy",
        "scikit-learn",
        "tensorflow",
        "pytorch",
        "tableau",
        "power bi",
        "hadoop",
        "spark",
    ],
    "devops": [
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "jenkins",
        "terraform",
        "ansible",
        "ci/cd",
        "linux",
        "shell scripting",
        "monitoring",
    ],
}
